### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by bodrovis** [uropb/MNA_next#1]
А на Heroku приложение залито?

**Comment by uropb** [comment]
Нет

**Comment by bodrovis** [comment]
Ну так надо - можно было поспрашивать у тех, кто уже сдавал :)

**Comment by uropb** [comment]
Илья подскажи что здесь не так.(устанавливаю на Heroku)
![1](https://f.cloud.github.com/assets/5879867/2386829/354a001c-a930-11e3-974b-5706c572f29d.jpg)

**Comment by uropb** [comment]
При открытии сайта пишется: We're sorry, but something went wrong.

**Comment by bodrovis** [comment]
Как вообще создавалось это приложение? https://github.com/uropb/MNA_next/blob/master/Rakefile здесь попытка обратиться к модулю `MNANext` (последняя строчка), но здесь https://github.com/uropb/MNA_next/blob/master/config/application.rb#L12 он почему-то называется `MNA`.

**Comment by uropb** [comment]
Да,странно.
Сейчас посмотрю...

**Comment by bodrovis** [comment]
Помимо этого нужно проделать все те действия для подготовки приложения перед публикацией на Heroku, о которых я рассказывал на лекции

**Comment by uropb** [comment]
Это?
group :production do
  gem 'pg'
end

**Comment by bodrovis** [comment]
В частности, да.http://railsapps.github.io/rails-heroku-tutorial.html вот ещё можно посмотреть, но шаги, связанные с rvm и библиотекой heroku пропускаем.

**Comment by uropb** [comment]
Всё сделал,залил,всё работает

http://mati-network-academy.herokuapp.com

**Comment by uropb** [comment]
Илья привет,у нас вопрос:
В прошлую среду я сдал экзамен и после(в субботу) Алексей Рошак, Сергей Юрьевич сказал уточнить оценки т.к. у нас экзамен.

**Comment by bodrovis** [comment]
Привет. Ок, тебе 5, Алексею 4
